### ISSUE TITLE
Update Models dependencies

### ISSUE THREAD

**Issue by nickevansuk** [openactive/dataset-site-template-php#10]
Looks like the library requires an older version of the Models library. We need to update the dependencies to allow it to work with 7.0 so we don't force users to downgrade the Models library to get this working.

**Comment by ylt** [comment]
Now released, https://github.com/openactive/dataset-site-template-php/releases/tag/v0.4.0 / https://packagist.org/packages/openactive/dataset-site#v0.4.0
